# -*- coding: utf-8 -*-
"""647_Seaborn_and_Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DSqlywAoEUK7DmQ1FbpbGcUIVeCmaWDp

# Introduction

Do higher film budgets lead to more box office revenue? Let's find out if there's a relationship using the movie budgets and financial performance data that I've scraped from [the-numbers.com](https://www.the-numbers.com/movie/budgets) on **May 1st, 2018**. 

<img src=https://i.imgur.com/kq7hrEh.png>

# Import Statements
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

"""# Notebook Presentation"""

pd.options.display.float_format = '{:,.2f}'.format

from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

"""# Read the Data"""

data = pd.read_csv('cost_revenue_dirty.csv')

"""# Explore and Clean the Data

**Challenge**: Answer these questions about the dataset:
1. How many rows and columns does the dataset contain?
2. Are there any NaN values present?
3. Are there any duplicate rows?
4. What are the data types of the columns?
"""

data.head()

data.tail()

data.sample(5)

data.shape

data.isnull().sum()

bool_series = data.duplicated()
bool_series

data[~bool_series]

data.info()

"""### Data Type Conversions

**Challenge**: Convert the `USD_Production_Budget`, `USD_Worldwide_Gross`, and `USD_Domestic_Gross` columns to a numeric format by removing `$` signs and `,`. 
<br>
<br>
Note that *domestic* in this context refers to the United States.
"""

target_cols = ['USD_Production_Budget', 'USD_Worldwide_Gross', 'USD_Domestic_Gross']

# data['USD_Production_Budget'] = data['USD_Production_Budget'].str.replace('$', '')
# data['USD_Production_Budget'] = data['USD_Production_Budget'].str.replace(',', '').astype('int')

## method 1
for col in target_cols:
    data[col] = data[col].str.replace('$', '')
    data[col] = data[col].str.replace(',', '').astype('int')

## method 2 ★
# chars_to_remove = [',', '$']
# columns_to_clean = ['USD_Production_Budget', 
#                     'USD_Worldwide_Gross',
#                     'USD_Domestic_Gross']
 
# for col in columns_to_clean:
#     for char in chars_to_remove:
#         # Replace each character with an empty string
#         data[col] = data[col].astype(str).str.replace(char, "")
#     # Convert column to a numeric data type
#     data[col] = pd.to_numeric(data[col])

data.head()

"""**Challenge**: Convert the `Release_Date` column to a Pandas Datetime type. """

data['Release_Date'] = pd.to_datetime(data['Release_Date'])

data.info()

"""### Descriptive Statistics

**Challenge**: 

1. What is the average production budget of the films in the data set?
2. What is the average worldwide gross revenue of films?
3. What were the minimums for worldwide and domestic revenue?
4. Are the bottom 25% of films actually profitable or do they lose money?
5. What are the highest production budget and highest worldwide gross revenue of any film?
6. How much revenue did the lowest and highest budget films make?
"""

data.describe()

data.USD_Production_Budget.mean()

data.USD_Worldwide_Gross.mean()

data.USD_Worldwide_Gross.min()

data.USD_Domestic_Gross.min()

data.USD_Worldwide_Gross.quantile(q = 0.25)

data.USD_Domestic_Gross.quantile(q = 0.25)

data.iloc[data.USD_Production_Budget.idxmax()]

data.iloc[data.USD_Worldwide_Gross.idxmax()]

data.iloc[data.USD_Worldwide_Gross.idxmin()]

data.iloc[data.USD_Production_Budget.idxmin()]

data[data.USD_Worldwide_Gross == 0].sort_values(by = 'USD_Production_Budget', ascending = False )

"""# Investigating the Zero Revenue Films

**Challenge** How many films grossed $0 domestically (i.e., in the United States)? What were the highest budget films that grossed nothing?
"""

data[data.USD_Domestic_Gross == 0].sort_values(by = 'USD_Production_Budget', ascending = False )

"""**Challenge**: How many films grossed $0 worldwide? What are the highest budget films that had no revenue internationally?"""

data[data.USD_Worldwide_Gross == 0].sort_values(by = 'USD_Production_Budget', ascending = False ).count()

"""### Filtering on Multiple Conditions"""

data.loc[(data.USD_Worldwide_Gross != 0) & (data.USD_Domestic_Gross == 0)]

"""**Challenge**: Use the [`.query()` function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html) to accomplish the same thing. Create a subset for international releases that had some worldwide gross revenue, but made zero revenue in the United States. 

Hint: This time you'll have to use the `and` keyword.
"""

# data.query('USD_Worldwide_Gross != 0' and 'USD_Domestic_Gross == 0' ) # ★ Wrong
data.query('USD_Worldwide_Gross != 0 and USD_Domestic_Gross == 0' )

"""### Unreleased Films

**Challenge**:
* Identify which films were not released yet as of the time of data collection (May 1st, 2018).
* How many films are included in the dataset that have not yet had a chance to be screened in the box office? 
* Create another DataFrame called data_clean that does not include these films. 
"""

# Date of Data Collection
scrape_date = pd.Timestamp('2018-5-1')
idx = data.query('Release_Date > @scrape_date and USD_Domestic_Gross == 0 and USD_Worldwide_Gross == 0 ').index

data_clean = data.drop(index = idx)

data_clean

print(type(data.Release_Date[0]))
type(scrape_date)

"""### Films that Lost Money

**Challenge**: 
What is the percentage of films where the production costs exceeded the worldwide gross revenue? 
"""

f'{len(data_clean[data_clean.USD_Worldwide_Gross < data_clean.USD_Production_Budget]) / data_clean.shape[0] * 100:.2f} %'

"""# Seaborn for Data Viz: Bubble Charts"""



plt.figure(figsize = (8,4), dpi = 200)
# set styling on a single chart
with sns.axes_style('darkgrid'):
    ax = sns.scatterplot(data = data_clean, x = 'USD_Production_Budget', y = 'USD_Worldwide_Gross', hue= 'USD_Worldwide_Gross', size = 'USD_Worldwide_Gross' )
    ax.set(ylim = (0, 3000000000), xlim = (0, 450000000), ylabel = 'Revenue in $ billions', xlabel = 'Budget in $100 millions')

"""### Plotting Movie Releases over Time

**Challenge**: Try to create the following Bubble Chart:

<img src=https://i.imgur.com/8fUn9T6.png>


"""

# data_clean['Year'] = data_clean.Release_Date.dt.year # no need
plt.figure(figsize = (6,4), dpi = 200)
# set styling on a single chart
with sns.axes_style('darkgrid'):
    ax = sns.scatterplot(data = data_clean, x = 'Release_Date', y = 'USD_Production_Budget', hue= 'USD_Worldwide_Gross', size = 'USD_Worldwide_Gross' )
    ax.set(ylim = (0, 450000000),xlim=(data_clean.Release_Date.min(),data_clean.Release_Date.max() ) , ylabel = 'Budge in $100 millions', xlabel = 'Year')
# plt.show()

"""# Converting Years to Decades Trick

**Challenge**: Create a column in `data_clean` that has the decade of the release. 

<img src=https://i.imgur.com/0VEfagw.png width=650> 

Here's how: 
1. Create a [`DatetimeIndex` object](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html) from the Release_Date column. 
2. Grab all the years from the `DatetimeIndex` object using the `.year` property.
<img src=https://i.imgur.com/5m06Ach.png width=650>
3. Use floor division `//` to convert the year data to the decades of the films.
4. Add the decades as a `Decade` column to the `data_clean` DataFrame.
"""

### Method 1
data_clean['Decade'] = (data_clean.set_index('Release_Date').index.year // 10) * 10 # ★

## Method 2
dt_index = pd.DatetimeIndex(data_clean.Release_Date)
years = dt_index.year

pd.DatetimeIndex(data_clean.Release_Date)

"""### Separate the "old" (before 1969) and "New" (1970s onwards) Films

**Challenge**: Create two new DataFrames: `old_films` and `new_films`
* `old_films` should include all the films before 1969 (up to and including 1969)
* `new_films` should include all the films from 1970 onwards
* How many films were released prior to 1970?
* What was the most expensive film made prior to 1970?
"""

data_clean.info()

old_films = data_clean[data_clean.Decade < 1970]
new_flims = data_clean[data_clean.Decade >= 1970]

old_films.describe()

new_flims.shape[0]

old_films.sort_values('USD_Production_Budget', ascending = False).head()

"""# Seaborn Regression Plots"""

plt.figure(figsize=(8,4), dpi = 200)
with sns.axes_style('whitegrid'): 
    sns.regplot(data = old_films, y = 'USD_Worldwide_Gross', x = 'USD_Production_Budget', scatter_kws = {'alpha': 0.4}, line_kws = {'color': 'black'} )

"""**Challenge**: Use Seaborn's `.regplot()` to show the scatter plot and linear regression line against the `new_films`. 
<br>
<br>
Style the chart

* Put the chart on a `'darkgrid'`.
* Set limits on the axes so that they don't show negative values.
* Label the axes on the plot "Revenue in \$ billions" and "Budget in \$ millions".
* Provide HEX colour codes for the plot and the regression line. Make the dots dark blue (#2f4b7c) and the line orange (#ff7c43).

Interpret the chart

* Do our data points for the new films align better or worse with the linear regression than for our older films?
* Roughly how much would a film with a budget of $150 million make according to the regression line?
"""

plt.figure(figsize=(8,4), dpi = 200)
with sns.axes_style('darkgrid'):
    ax = sns.regplot(data = new_flims ,y = 'USD_Worldwide_Gross', x = 'USD_Production_Budget', color =  '#2f4b7c', scatter_kws = {'alpha': 0.3 }, line_kws = {'color': '#ff7c43'} )
    ax.set(xlim=(0, None), ylim=(0, 3000000000), xlabel= 'Budget in $ millions', ylabel ='Revenue in $ billions'  )

"""# Run Your Own Regression with scikit-learn

$$ REV \hat ENUE = \theta _0 + \theta _1 BUDGET$$
"""

regression = LinearRegression()

"""**Challenge**: Run a linear regression for the `old_films`. Calculate the intercept, slope and r-squared. How much of the variance in movie revenue does the linear model explain in this case?"""

## Method 1
# X = pd.DataFrame(new_flims, columns = ['USD_Production_Budget']) # print(X, type(X)) [5231 rows x 1 columns] <class 'pandas.core.frame.DataFrame'>
# y = pd.DataFrame(new_flims, columns = ['USD_Worldwide_Gross']) # ★ Our LinearRegression does not like receiving Pandas Series 

## Method 2
X = new_flims['USD_Production_Budget'].values.reshape(-1, 1)
y = new_flims['USD_Worldwide_Gross'].values.reshape(-1, 1)

regression.fit(X,y)
print(regression.intercept_)
print(regression.coef_)
# R-squared
regression.score(X, y)

X = pd.DataFrame(old_films, columns = ['USD_Production_Budget'])
y = pd.DataFrame(old_films, columns = ['USD_Worldwide_Gross'])

regression.fit(X,y)
print(f'The slope coefficient is: {regression.coef_[0]}')
print(f'The intercept is: {regression.intercept_[0]}')
print(f'The slope coefficient is: {regression.score(X, y)}')
import numpy as np
regression.predict(np.array(350000000).reshape(-1, 1))

print(22821538 + 1.64771314 * 350000000)

budget = 350000000
revenue_estimate = regression.intercept_[0] + regression.coef_[0,0]*budget
revenue_estimate = round(revenue_estimate, -6)
print(f'The estimated revenue for a $350 film is around ${revenue_estimate:.10}.')

"""# Use Your Model to Make a Prediction

We just estimated the slope and intercept! Remember that our Linear Model has the following form:

$$ REV \hat ENUE = \theta _0 + \theta _1 BUDGET$$

**Challenge**:  How much global revenue does our model estimate for a film with a budget of $350 million? 
"""



